import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:zera_erp/features/authentication/application/auth_providers.dart';
import 'package:zera_erp/features/authentication/application/auth_state.dart';
import 'package:zera_erp/features/authentication/domain/entities/auth_user.dart';
import 'package:zera_erp/features/freelancers/application/freelancers_providers.dart';
import 'package:zera_erp/features/payroll/application/payroll_providers.dart';
import 'package:zera_erp/features/payroll/domain/entities/payroll_department_total.dart';
import 'package:zera_erp/features/payroll/domain/entities/payroll_run_status.dart';
import 'package:zera_erp/features/payroll/presentation/pages/payroll_run_detail_page.dart';

import '../../helpers/fake_auth.dart';
import '../../helpers/fake_freelancers.dart';
import '../../helpers/fake_payroll.dart';

const _superAdmin = AuthUser(
  id: 'admin-1',
  email: 'admin@zeracreative.com',
  role: 'Super Admin',
  permissions: ['payroll.manage'],
);

Widget _app({
  required FakePayrollRepository repository,
  String runId = 'run-1',
  FakeFreelancersRepository? freelancersRepository,
}) {
  return ProviderScope(
    overrides: [
      authControllerProvider.overrideWith(
        (ref) => PresetAuthController(AuthAuthenticated(_superAdmin)),
      ),
      payrollRepositoryProvider.overrideWithValue(repository),
      freelancersRepositoryProvider.overrideWithValue(
        freelancersRepository ?? FakeFreelancersRepository(),
      ),
    ],
    child: MaterialApp(home: PayrollRunDetailPage(runId: runId)),
  );
}

void main() {
  testWidgets('shows run info and line items', (tester) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        month: 8,
        year: 2026,
        status: PayrollRunStatus.draft,
        generatedByName: 'Noushad Ranani',
        lineItems: [
          buildTestPayrollLineItem(
            employeeName: 'Jane Doe',
            baseSalary: 50000,
            deductions: 2000,
          ),
        ],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.text('August 2026'), findsOneWidget);
    expect(find.text('Generated by Noushad Ranani'), findsOneWidget);
    expect(find.text('Jane Doe'), findsOneWidget);
    expect(find.text('50,000.00'), findsOneWidget); // base salary
    expect(find.text('48,000.00'), findsOneWidget); // net pay
  });

  testWidgets('shows Finalize for a draft run, and Mark Paid after finalizing', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.draft),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Finalize'), findsOneWidget);
    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsNothing);

    await tester.tap(find.widgetWithText(FilledButton, 'Finalize'));
    await tester.pumpAndSettle();

    expect(repository.lastFinalizedRunId, 'run-1');
  });

  testWidgets('shows Mark Paid for a finalized run and calls payRun', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.finalized),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsOneWidget);

    await tester.tap(find.widgetWithText(FilledButton, 'Mark Paid'));
    await tester.pumpAndSettle();

    expect(repository.lastPaidRunId, 'run-1');
  });

  testWidgets('hides both action buttons once a run is paid', (tester) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.paid),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Finalize'), findsNothing);
    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsNothing);
  });

  testWidgets(
    'editing a line item in a draft run submits new additions/deductions',
    (tester) async {
      final repository = FakePayrollRepository(
        runDetail: buildTestPayrollRunDetail(
          status: PayrollRunStatus.draft,
          lineItems: [buildTestPayrollLineItem(id: 'item-9', employeeName: 'Jane Doe')],
        ),
      );
      await tester.pumpWidget(_app(repository: repository));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Jane Doe'));
      await tester.pumpAndSettle();

      expect(find.text('Jane Doe'), findsWidgets); // dialog title + table cell

      await tester.enterText(
        find.widgetWithText(TextField, 'Additions (PKR)'),
        '500',
      );
      await tester.enterText(
        find.widgetWithText(TextField, 'Deductions (PKR)'),
        '2000',
      );
      await tester.pumpAndSettle();

      expect(find.textContaining('PKR 48,500.00'), findsOneWidget);

      await tester.tap(find.widgetWithText(FilledButton, 'Save'));
      await tester.pumpAndSettle();

      expect(repository.lastUpdatedLineItemId, 'item-9');
      expect(repository.lastUpdatedAdditions, 500);
      expect(repository.lastUpdatedDeductions, 2000);
    },
  );

  testWidgets(
    'editing piece-rate quantity and per-unit rate submits both',
    (tester) async {
      final repository = FakePayrollRepository(
        runDetail: buildTestPayrollRunDetail(
          status: PayrollRunStatus.draft,
          lineItems: [
            buildTestPayrollLineItem(id: 'item-9', employeeName: 'Kulsum Zehra'),
          ],
        ),
      );
      await tester.pumpWidget(_app(repository: repository));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Kulsum Zehra'));
      await tester.pumpAndSettle();

      await tester.enterText(find.widgetWithText(TextField, 'Quantity'), '5');
      await tester.enterText(
        find.widgetWithText(TextField, 'Per unit (PKR)'),
        '1000',
      );
      await tester.tap(find.widgetWithText(FilledButton, 'Save'));
      await tester.pumpAndSettle();

      expect(repository.lastUpdatedQuantity, 5);
      expect(repository.lastUpdatedPerUnitRate, 1000);
    },
  );

  testWidgets('does not open the edit dialog for a finalized run\'s line items', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        status: PayrollRunStatus.finalized,
        lineItems: [buildTestPayrollLineItem(employeeName: 'Jane Doe')],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Jane Doe'));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(TextField, 'Additions (PKR)'), findsNothing);
  });

  testWidgets(
    'the line items table shows Employee, Base, Additions, Deductions, and Net Pay',
    (tester) async {
      final repository = FakePayrollRepository(
        runDetail: buildTestPayrollRunDetail(
          status: PayrollRunStatus.draft,
          lineItems: [
            buildTestPayrollLineItem(
              employeeName: 'Jane Doe',
              baseSalary: 50000,
              deductions: 2000,
            ),
          ],
        ),
      );
      await tester.pumpWidget(_app(repository: repository));
      await tester.pumpAndSettle();

      expect(find.text('Employee'), findsOneWidget);
      expect(find.text('Base'), findsOneWidget);
      expect(find.text('Additions'), findsOneWidget);
      expect(find.text('Deductions'), findsOneWidget);
      expect(find.text('Net Pay'), findsOneWidget);
      expect(find.text('-2,000.00'), findsOneWidget);
      expect(find.text('Fines'), findsNothing);
      expect(find.text('Absent'), findsNothing);
      expect(find.text('Late Days'), findsNothing);
    },
  );

  testWidgets(
    "a freelancer's line item shows a Freelancer badge and an editable "
    'amount instead of a read-only salary snapshot',
    (tester) async {
      final repository = FakePayrollRepository(
        runDetail: buildTestPayrollRunDetail(
          status: PayrollRunStatus.draft,
          lineItems: [
            buildTestPayrollLineItem(
              employeeName: 'Kulsum Zehra',
              freelancerId: 'freelancer-1',
              isFreelancer: true,
              employeeId: null,
              baseSalary: 27300,
            ),
          ],
        ),
      );
      await tester.pumpWidget(_app(repository: repository));
      await tester.pumpAndSettle();

      expect(find.text('Freelancer'), findsOneWidget);

      await tester.tap(find.text('Kulsum Zehra'));
      await tester.pumpAndSettle();

      expect(find.text('Salary snapshot: PKR 27,300.00'), findsNothing);
      expect(
        find.widgetWithText(TextField, "This month's pay (PKR)"),
        findsOneWidget,
      );

      await tester.enterText(
        find.widgetWithText(TextField, "This month's pay (PKR)"),
        '30000',
      );
      await tester.tap(find.widgetWithText(FilledButton, 'Save'));
      await tester.pumpAndSettle();

      expect(repository.lastUpdatedBaseSalary, 30000);
    },
  );

  testWidgets(
    'tapping Add Freelancer submits the selected freelancer and amount',
    (tester) async {
      final repository = FakePayrollRepository(
        runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.draft),
      );
      await tester.pumpWidget(
        _app(
          repository: repository,
          freelancersRepository: FakeFreelancersRepository(
            freelancers: [
              buildTestFreelancer(
                id: 'freelancer-2',
                fullName: 'Hamza Saqib',
              ),
            ],
          ),
        ),
      );
      await tester.pumpAndSettle();

      await tester.tap(find.widgetWithText(OutlinedButton, 'Add Freelancer'));
      await tester.pumpAndSettle();

      await tester.tap(
        find.widgetWithText(DropdownButtonFormField<String>, 'Freelancer'),
      );
      await tester.pumpAndSettle();
      await tester.tap(find.text('Hamza Saqib').last);
      await tester.pumpAndSettle();

      await tester.enterText(
        find.widgetWithText(TextField, "This month's pay (PKR)"),
        '27300',
      );
      await tester.tap(find.widgetWithText(FilledButton, 'Add'));
      await tester.pumpAndSettle();

      expect(repository.lastAddedFreelancerRunId, 'run-1');
      expect(repository.lastAddedFreelancerId, 'freelancer-2');
      expect(repository.lastAddedFreelancerBaseSalary, 27300);
    },
  );

  testWidgets('shows a Payroll by Department breakdown for this run', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        status: PayrollRunStatus.draft,
        lineItems: [
          buildTestPayrollLineItem(baseSalary: 80000),
          buildTestPayrollLineItem(id: 'item-2', baseSalary: 20000),
        ],
        departmentTotals: const [
          PayrollDepartmentTotal(
            departmentId: 'dept-eng',
            departmentName: 'Engineering',
            totalNetPay: 80000,
            itemCount: 1,
          ),
          PayrollDepartmentTotal(
            departmentId: null,
            departmentName: 'Freelancers',
            totalNetPay: 20000,
            itemCount: 1,
          ),
        ],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.text('Payroll by Department'), findsOneWidget);
    expect(find.text('Engineering'), findsOneWidget);
    expect(find.text('80.0% of payroll'), findsOneWidget);
    expect(find.text('PKR 80,000 · 1 person'), findsOneWidget);
    expect(find.text('Freelancers'), findsOneWidget);
    expect(find.text('20.0% of payroll'), findsOneWidget);
    expect(find.text('PKR 20,000 · 1 person'), findsOneWidget);
  });
}
