import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:zera_erp/features/authentication/application/auth_providers.dart';
import 'package:zera_erp/features/authentication/application/auth_state.dart';
import 'package:zera_erp/features/authentication/domain/entities/auth_user.dart';
import 'package:zera_erp/features/payroll/application/payroll_providers.dart';
import 'package:zera_erp/features/payroll/domain/entities/payroll_run_status.dart';
import 'package:zera_erp/features/payroll/presentation/pages/payroll_run_detail_page.dart';

import '../../helpers/fake_auth.dart';
import '../../helpers/fake_payroll.dart';

const _superAdmin = AuthUser(
  id: 'admin-1',
  email: 'admin@zeracreative.com',
  role: 'Super Admin',
  permissions: ['payroll.manage'],
);

Widget _app({required FakePayrollRepository repository, String runId = 'run-1'}) {
  return ProviderScope(
    overrides: [
      authControllerProvider.overrideWith(
        (ref) => PresetAuthController(AuthAuthenticated(_superAdmin)),
      ),
      payrollRepositoryProvider.overrideWithValue(repository),
    ],
    child: MaterialApp(home: PayrollRunDetailPage(runId: runId)),
  );
}

void main() {
  testWidgets('shows run info and line items', (tester) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        month: 8,
        year: 2026,
        status: PayrollRunStatus.draft,
        generatedByName: 'Noushad Ranani',
        lineItems: [
          buildTestPayrollLineItem(
            employeeName: 'Jane Doe',
            baseSalary: 50000,
            bonuses: 5000,
          ),
        ],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.text('August 2026'), findsOneWidget);
    expect(find.text('Generated by Noushad Ranani'), findsOneWidget);
    expect(find.text('Jane Doe'), findsOneWidget);
    expect(find.text('55,000.00'), findsOneWidget); // net pay
  });

  testWidgets('shows Finalize for a draft run, and Mark Paid after finalizing', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.draft),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Finalize'), findsOneWidget);
    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsNothing);

    await tester.tap(find.widgetWithText(FilledButton, 'Finalize'));
    await tester.pumpAndSettle();

    expect(repository.lastFinalizedRunId, 'run-1');
  });

  testWidgets('shows Mark Paid for a finalized run and calls payRun', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.finalized),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsOneWidget);

    await tester.tap(find.widgetWithText(FilledButton, 'Mark Paid'));
    await tester.pumpAndSettle();

    expect(repository.lastPaidRunId, 'run-1');
  });

  testWidgets('hides both action buttons once a run is paid', (tester) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(status: PayrollRunStatus.paid),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(FilledButton, 'Finalize'), findsNothing);
    expect(find.widgetWithText(FilledButton, 'Mark Paid'), findsNothing);
  });

  testWidgets('editing a line item in a draft run submits the new figures', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        status: PayrollRunStatus.draft,
        lineItems: [buildTestPayrollLineItem(id: 'item-9', employeeName: 'Jane Doe')],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Jane Doe'));
    await tester.pumpAndSettle();

    expect(find.text('Jane Doe'), findsWidgets); // dialog title + table cell

    await tester.enterText(find.widgetWithText(TextField, 'Bonuses (PKR)'), '5000');
    await tester.tap(find.widgetWithText(FilledButton, 'Save'));
    await tester.pumpAndSettle();

    expect(repository.lastUpdatedLineItemId, 'item-9');
    expect(repository.lastUpdatedBonuses, 5000);
  });

  testWidgets('does not open the edit dialog for a finalized run\'s line items', (
    tester,
  ) async {
    final repository = FakePayrollRepository(
      runDetail: buildTestPayrollRunDetail(
        status: PayrollRunStatus.finalized,
        lineItems: [buildTestPayrollLineItem(employeeName: 'Jane Doe')],
      ),
    );
    await tester.pumpWidget(_app(repository: repository));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Jane Doe'));
    await tester.pumpAndSettle();

    expect(find.widgetWithText(TextField, 'Bonuses (PKR)'), findsNothing);
  });
}
