import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../shared/utils/currency_format.dart';
import '../../../../shared/utils/date_format.dart';
import '../../../../shared/widgets/form_section.dart';
import '../../application/payroll_providers.dart';
import '../../domain/entities/payroll_line_item.dart';
import '../../domain/entities/payroll_run_detail.dart';
import '../../domain/entities/payroll_run_status.dart';
import '../../domain/exceptions/payroll_exception.dart';
import '../widgets/payroll_run_status_badge.dart';

class PayrollRunDetailPage extends ConsumerWidget {
  const PayrollRunDetailPage({super.key, required this.runId});

  final String runId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final runAsync = ref.watch(payrollRunDetailProvider(runId));

    return Scaffold(
      appBar: AppBar(title: const Text('Payroll Run')),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 1000),
            child: runAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (_, _) => Text(
                'Could not load this payroll run. Please try again.',
                style: TextStyle(color: Theme.of(context).colorScheme.error),
              ),
              data: (run) => _RunDetailBody(run: run),
            ),
          ),
        ),
      ),
    );
  }
}

class _RunDetailBody extends ConsumerWidget {
  const _RunDetailBody({required this.run});

  final PayrollRunDetail run;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          FormSection(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      formatPayrollRunPeriod(run.month, run.year),
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    PayrollRunStatusBadge(status: run.status),
                  ],
                ),
                const SizedBox(height: 8),
                Text('Generated by ${run.generatedByName}'),
                if (run.finalizedByName != null)
                  Text(
                    'Finalized by ${run.finalizedByName} · '
                    '${formatDisplayDateTime(run.finalizedAt!)}',
                  ),
                if (run.paidByName != null)
                  Text(
                    'Paid by ${run.paidByName} · '
                    '${formatDisplayDateTime(run.paidAt!)}',
                  ),
                const SizedBox(height: 12),
                Text(
                  'Total net pay: PKR ${formatAmount(run.totalNetPay)}',
                  style: Theme.of(
                    context,
                  ).textTheme.titleMedium?.copyWith(color: AppColors.primary),
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    if (run.status == PayrollRunStatus.draft)
                      FilledButton.icon(
                        onPressed: () async {
                          try {
                            await ref
                                .read(payrollRepositoryProvider)
                                .finalizeRun(run.id);
                            ref.invalidate(payrollRunDetailProvider(run.id));
                            ref.invalidate(payrollRunsListProvider);
                          } on PayrollException catch (error) {
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(content: Text(error.message)),
                              );
                            }
                          }
                        },
                        icon: const Icon(Icons.lock_outline, size: 16),
                        label: const Text('Finalize'),
                      ),
                    if (run.status == PayrollRunStatus.finalized)
                      FilledButton.icon(
                        onPressed: () async {
                          try {
                            await ref
                                .read(payrollRepositoryProvider)
                                .payRun(run.id);
                            ref.invalidate(payrollRunDetailProvider(run.id));
                            ref.invalidate(payrollRunsListProvider);
                          } on PayrollException catch (error) {
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(content: Text(error.message)),
                              );
                            }
                          }
                        },
                        icon: const Icon(Icons.payments_outlined, size: 16),
                        label: const Text('Mark Paid'),
                      ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          FormSection(
            title: 'Line items',
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: DataTable(
                columns: const [
                  DataColumn(label: Text('Employee')),
                  DataColumn(label: Text('Base'), numeric: true),
                  DataColumn(label: Text('Qty'), numeric: true),
                  DataColumn(label: Text('Rate'), numeric: true),
                  DataColumn(label: Text('Allowances'), numeric: true),
                  DataColumn(label: Text('Overtime'), numeric: true),
                  DataColumn(label: Text('Reimbursement'), numeric: true),
                  DataColumn(label: Text('Commissions'), numeric: true),
                  DataColumn(label: Text('Deductions'), numeric: true),
                  DataColumn(label: Text('Fines'), numeric: true),
                  DataColumn(label: Text('Absent'), numeric: true),
                  DataColumn(label: Text('Absent Ded.'), numeric: true),
                  DataColumn(label: Text('Late Hrs'), numeric: true),
                  DataColumn(label: Text('Late Hrs Ded.'), numeric: true),
                  DataColumn(label: Text('Late Days'), numeric: true),
                  DataColumn(label: Text('Late Days Ded.'), numeric: true),
                  DataColumn(label: Text('Advances'), numeric: true),
                  DataColumn(label: Text('Tax'), numeric: true),
                  DataColumn(label: Text('Net Pay'), numeric: true),
                ],
                rows: [
                  for (final item in run.lineItems)
                    DataRow(
                      onSelectChanged: run.status == PayrollRunStatus.draft
                          ? (_) async {
                              await showDialog<void>(
                                context: context,
                                builder: (_) => _EditLineItemDialog(
                                  runId: run.id,
                                  item: item,
                                ),
                              );
                              ref.invalidate(payrollRunDetailProvider(run.id));
                              ref.invalidate(payrollRunsListProvider);
                            }
                          : null,
                      cells: [
                        DataCell(Text(item.employeeName)),
                        DataCell(Text(formatAmount(item.baseSalary))),
                        DataCell(Text(item.quantity == null ? '—' : '${item.quantity}')),
                        DataCell(
                          Text(
                            item.perUnitRate == null
                                ? '—'
                                : formatAmount(item.perUnitRate!),
                          ),
                        ),
                        DataCell(Text(formatAmount(item.allowances))),
                        DataCell(Text(formatAmount(item.overtime))),
                        DataCell(Text(formatAmount(item.reimbursement))),
                        DataCell(Text(formatAmount(item.commissions))),
                        DataCell(Text(formatAmount(item.deductions))),
                        DataCell(Text(formatAmount(item.fines))),
                        DataCell(Text('${item.totalAbsent}')),
                        DataCell(Text(formatAmount(item.absentDeductionRs))),
                        DataCell(Text('${item.lateHours}')),
                        DataCell(Text(formatAmount(item.lateHoursDeductionRs))),
                        DataCell(Text('${item.lateDays}')),
                        DataCell(Text(formatAmount(item.lateDaysDeductionRs))),
                        DataCell(Text(formatAmount(item.advances))),
                        DataCell(Text(formatAmount(item.tax))),
                        DataCell(
                          Text(
                            formatAmount(item.netPay),
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                        ),
                      ],
                    ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _EditLineItemDialog extends ConsumerStatefulWidget {
  const _EditLineItemDialog({required this.runId, required this.item});

  final String runId;
  final PayrollLineItem item;

  @override
  ConsumerState<_EditLineItemDialog> createState() =>
      _EditLineItemDialogState();
}

class _EditLineItemDialogState extends ConsumerState<_EditLineItemDialog> {
  late final TextEditingController _quantityController;
  late final TextEditingController _perUnitRateController;
  late final TextEditingController _allowancesController;
  late final TextEditingController _overtimeController;
  late final TextEditingController _reimbursementController;
  late final TextEditingController _commissionsController;
  late final TextEditingController _deductionsController;
  late final TextEditingController _finesController;
  late final TextEditingController _totalAbsentController;
  late final TextEditingController _lateHoursController;
  late final TextEditingController _lateDaysController;
  late final TextEditingController _advancesController;
  late final TextEditingController _taxController;
  late final TextEditingController _notesController;
  bool _saving = false;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _quantityController = TextEditingController(
      text: widget.item.quantity == null ? '' : '${widget.item.quantity}',
    );
    _perUnitRateController = TextEditingController(
      text: widget.item.perUnitRate?.toStringAsFixed(2) ?? '',
    );
    _allowancesController = TextEditingController(
      text: widget.item.allowances.toStringAsFixed(2),
    );
    _overtimeController = TextEditingController(
      text: widget.item.overtime.toStringAsFixed(2),
    );
    _reimbursementController = TextEditingController(
      text: widget.item.reimbursement.toStringAsFixed(2),
    );
    _commissionsController = TextEditingController(
      text: widget.item.commissions.toStringAsFixed(2),
    );
    _deductionsController = TextEditingController(
      text: widget.item.deductions.toStringAsFixed(2),
    );
    _finesController = TextEditingController(
      text: widget.item.fines.toStringAsFixed(2),
    );
    _totalAbsentController = TextEditingController(
      text: '${widget.item.totalAbsent}',
    );
    _lateHoursController = TextEditingController(
      text: '${widget.item.lateHours}',
    );
    _lateDaysController = TextEditingController(
      text: '${widget.item.lateDays}',
    );
    _advancesController = TextEditingController(
      text: widget.item.advances.toStringAsFixed(2),
    );
    _taxController = TextEditingController(
      text: widget.item.tax.toStringAsFixed(2),
    );
    _notesController = TextEditingController(text: widget.item.notes ?? '');
  }

  @override
  void dispose() {
    _quantityController.dispose();
    _perUnitRateController.dispose();
    _allowancesController.dispose();
    _overtimeController.dispose();
    _reimbursementController.dispose();
    _commissionsController.dispose();
    _deductionsController.dispose();
    _finesController.dispose();
    _totalAbsentController.dispose();
    _lateHoursController.dispose();
    _lateDaysController.dispose();
    _advancesController.dispose();
    _taxController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    setState(() {
      _saving = true;
      _errorMessage = null;
    });
    try {
      await ref
          .read(payrollRepositoryProvider)
          .updateLineItem(
            widget.runId,
            widget.item.id,
            quantity: int.tryParse(_quantityController.text),
            perUnitRate: double.tryParse(_perUnitRateController.text),
            allowances: double.tryParse(_allowancesController.text) ?? 0,
            overtime: double.tryParse(_overtimeController.text) ?? 0,
            reimbursement:
                double.tryParse(_reimbursementController.text) ?? 0,
            commissions: double.tryParse(_commissionsController.text) ?? 0,
            deductions: double.tryParse(_deductionsController.text) ?? 0,
            fines: double.tryParse(_finesController.text) ?? 0,
            totalAbsent: int.tryParse(_totalAbsentController.text) ?? 0,
            lateHours: int.tryParse(_lateHoursController.text) ?? 0,
            lateDays: int.tryParse(_lateDaysController.text) ?? 0,
            advances: double.tryParse(_advancesController.text) ?? 0,
            tax: double.tryParse(_taxController.text) ?? 0,
            notes: _notesController.text.trim().isEmpty
                ? null
                : _notesController.text.trim(),
          );
      if (mounted) Navigator.of(context).pop();
    } on PayrollException catch (error) {
      setState(() => _errorMessage = error.message);
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.item.employeeName),
      content: SizedBox(
        width: 420,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              if (_errorMessage != null) ...[
                Text(
                  _errorMessage!,
                  style: TextStyle(color: Theme.of(context).colorScheme.error),
                ),
                const SizedBox(height: 12),
              ],
              Text(
                'Salary snapshot: PKR ${formatAmount(widget.item.baseSalary)}',
                style: Theme.of(
                  context,
                ).textTheme.bodySmall?.copyWith(color: AppColors.textSecondary),
              ),
              const SizedBox(height: 16),
              const _SectionLabel('Piece-rate pay (optional)'),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _quantityController,
                      enabled: !_saving,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(labelText: 'Quantity'),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _AmountField(
                      label: 'Per unit',
                      controller: _perUnitRateController,
                      enabled: !_saving,
                    ),
                  ),
                ],
              ),
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text(
                  'When both are set, Quantity × Per unit replaces the salary '
                  'snapshot as this run\'s base pay.',
                  style: Theme.of(context).textTheme.labelSmall?.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
              ),
              const SizedBox(height: 16),
              const _SectionLabel('Additions'),
              const SizedBox(height: 8),
              _AmountField(label: 'Allowances', controller: _allowancesController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Overtime', controller: _overtimeController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Reimbursement', controller: _reimbursementController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Commissions/Incentives', controller: _commissionsController, enabled: !_saving),
              const SizedBox(height: 16),
              const _SectionLabel('Attendance deductions'),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _totalAbsentController,
                      enabled: !_saving,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Absent days',
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: TextField(
                      controller: _lateHoursController,
                      enabled: !_saving,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(labelText: 'Late hours'),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              TextField(
                controller: _lateDaysController,
                enabled: !_saving,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  labelText: 'Late-arrival days',
                  helperText: 'Every 3 late days deducts one unpaid day\'s pay',
                ),
              ),
              const SizedBox(height: 16),
              const _SectionLabel('Other deductions'),
              const SizedBox(height: 8),
              _AmountField(label: 'Deductions', controller: _deductionsController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Fines', controller: _finesController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Advances', controller: _advancesController, enabled: !_saving),
              const SizedBox(height: 12),
              _AmountField(label: 'Tax', controller: _taxController, enabled: !_saving),
              const SizedBox(height: 16),
              TextField(
                controller: _notesController,
                enabled: !_saving,
                maxLines: 2,
                decoration: const InputDecoration(labelText: 'Notes (optional)'),
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _saving ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: _saving ? null : _submit,
          child: _saving
              ? const SizedBox(
                  height: 16,
                  width: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Save'),
        ),
      ],
    );
  }
}

class _SectionLabel extends StatelessWidget {
  const _SectionLabel(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Text(
      text.toUpperCase(),
      style: Theme.of(context).textTheme.labelSmall?.copyWith(
        color: AppColors.textSecondary,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.4,
      ),
    );
  }
}

class _AmountField extends StatelessWidget {
  const _AmountField({
    required this.label,
    required this.controller,
    required this.enabled,
  });

  final String label;
  final TextEditingController controller;
  final bool enabled;

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: controller,
      enabled: enabled,
      keyboardType: const TextInputType.numberWithOptions(decimal: true),
      decoration: InputDecoration(labelText: '$label (PKR)'),
    );
  }
}
