import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../shared/utils/currency_format.dart';
import '../../../../shared/utils/date_format.dart';
import '../../../../shared/widgets/department_breakdown_section.dart';
import '../../../../shared/widgets/form_section.dart';
import '../../../freelancers/application/freelancers_providers.dart';
import '../../application/payroll_providers.dart';
import '../../domain/entities/payroll_line_item.dart';
import '../../domain/entities/payroll_run_detail.dart';
import '../../domain/entities/payroll_run_status.dart';
import '../../domain/exceptions/payroll_exception.dart';
import '../widgets/payroll_run_status_badge.dart';

class PayrollRunDetailPage extends ConsumerWidget {
  const PayrollRunDetailPage({super.key, required this.runId});

  final String runId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final runAsync = ref.watch(payrollRunDetailProvider(runId));

    return Scaffold(
      appBar: AppBar(title: const Text('Payroll Run')),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 1000),
            child: runAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (_, _) => Text(
                'Could not load this payroll run. Please try again.',
                style: TextStyle(color: Theme.of(context).colorScheme.error),
              ),
              data: (run) => _RunDetailBody(run: run),
            ),
          ),
        ),
      ),
    );
  }
}

class _RunDetailBody extends ConsumerWidget {
  const _RunDetailBody({required this.run});

  final PayrollRunDetail run;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          FormSection(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      formatPayrollRunPeriod(run.month, run.year),
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    PayrollRunStatusBadge(status: run.status),
                  ],
                ),
                const SizedBox(height: 8),
                Text('Generated by ${run.generatedByName}'),
                if (run.finalizedByName != null)
                  Text(
                    'Finalized by ${run.finalizedByName} · '
                    '${formatDisplayDateTime(run.finalizedAt!)}',
                  ),
                if (run.paidByName != null)
                  Text(
                    'Paid by ${run.paidByName} · '
                    '${formatDisplayDateTime(run.paidAt!)}',
                  ),
                const SizedBox(height: 12),
                Text(
                  'Total net pay: PKR ${formatAmount(run.totalNetPay)}',
                  style: Theme.of(
                    context,
                  ).textTheme.titleMedium?.copyWith(color: AppColors.primary),
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    if (run.status == PayrollRunStatus.draft)
                      FilledButton.icon(
                        onPressed: () async {
                          try {
                            await ref
                                .read(payrollRepositoryProvider)
                                .finalizeRun(run.id);
                            ref.invalidate(payrollRunDetailProvider(run.id));
                            ref.invalidate(payrollRunsListProvider);
                          } on PayrollException catch (error) {
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(content: Text(error.message)),
                              );
                            }
                          }
                        },
                        icon: const Icon(Icons.lock_outline, size: 16),
                        label: const Text('Finalize'),
                      ),
                    if (run.status == PayrollRunStatus.finalized)
                      FilledButton.icon(
                        onPressed: () async {
                          try {
                            await ref
                                .read(payrollRepositoryProvider)
                                .payRun(run.id);
                            ref.invalidate(payrollRunDetailProvider(run.id));
                            ref.invalidate(payrollRunsListProvider);
                          } on PayrollException catch (error) {
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(content: Text(error.message)),
                              );
                            }
                          }
                        },
                        icon: const Icon(Icons.payments_outlined, size: 16),
                        label: const Text('Mark Paid'),
                      ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          DepartmentBreakdownSection(
            title: 'Payroll by Department',
            totalAmount: run.totalNetPay,
            countLabel: (count) => count == 1 ? '1 person' : '$count people',
            rows: [
              for (final total in run.departmentTotals)
                DepartmentBreakdownRow(
                  name: total.departmentName,
                  amount: total.totalNetPay,
                  count: total.itemCount,
                ),
            ],
          ),
          const SizedBox(height: 16),
          FormSection(
            title: 'Line items',
            trailing: run.status == PayrollRunStatus.draft
                ? OutlinedButton.icon(
                    onPressed: () async {
                      await showDialog<void>(
                        context: context,
                        builder: (_) => _AddFreelancerDialog(run: run),
                      );
                      ref.invalidate(payrollRunDetailProvider(run.id));
                      ref.invalidate(payrollRunsListProvider);
                    },
                    icon: const Icon(Icons.person_add_alt_outlined, size: 16),
                    label: const Text('Add Freelancer'),
                  )
                : null,
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: DataTable(
                columns: const [
                  DataColumn(label: Text('Employee')),
                  DataColumn(label: Text('Base'), numeric: true),
                  DataColumn(label: Text('Additions'), numeric: true),
                  DataColumn(label: Text('Deductions'), numeric: true),
                  DataColumn(label: Text('Net Pay'), numeric: true),
                ],
                rows: [
                  for (final item in run.lineItems)
                    DataRow(
                      onSelectChanged: run.status == PayrollRunStatus.draft
                          ? (_) async {
                              await showDialog<void>(
                                context: context,
                                builder: (_) => _EditLineItemDialog(
                                  runId: run.id,
                                  item: item,
                                ),
                              );
                              ref.invalidate(payrollRunDetailProvider(run.id));
                              ref.invalidate(payrollRunsListProvider);
                            }
                          : null,
                      cells: [
                        DataCell(
                          item.isFreelancer
                              ? Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Text(item.employeeName),
                                    const SizedBox(width: 6),
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 6,
                                        vertical: 2,
                                      ),
                                      decoration: BoxDecoration(
                                        color: AppColors.primary.withValues(
                                          alpha: 0.1,
                                        ),
                                        borderRadius: BorderRadius.circular(6),
                                      ),
                                      child: Text(
                                        'Freelancer',
                                        style: Theme.of(context)
                                            .textTheme
                                            .labelSmall
                                            ?.copyWith(color: AppColors.primary),
                                      ),
                                    ),
                                  ],
                                )
                              : Text(item.employeeName),
                        ),
                        DataCell(Text(formatAmount(item.baseSalary))),
                        DataCell(
                          Text(
                            item.additions == 0
                                ? '—'
                                : '+${formatAmount(item.additions)}',
                            style: item.additions == 0
                                ? null
                                : const TextStyle(color: AppColors.success),
                          ),
                        ),
                        DataCell(
                          Text(
                            item.deductions == 0
                                ? '—'
                                : '-${formatAmount(item.deductions)}',
                            style: item.deductions == 0
                                ? null
                                : const TextStyle(color: AppColors.error),
                          ),
                        ),
                        DataCell(
                          Text(
                            formatAmount(item.netPay),
                            style: const TextStyle(fontWeight: FontWeight.w600),
                          ),
                        ),
                      ],
                    ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _EditLineItemDialog extends ConsumerStatefulWidget {
  const _EditLineItemDialog({required this.runId, required this.item});

  final String runId;
  final PayrollLineItem item;

  @override
  ConsumerState<_EditLineItemDialog> createState() =>
      _EditLineItemDialogState();
}

class _EditLineItemDialogState extends ConsumerState<_EditLineItemDialog> {
  late final TextEditingController _baseSalaryController;
  late final TextEditingController _quantityController;
  late final TextEditingController _perUnitRateController;
  late final TextEditingController _additionsController;
  late final TextEditingController _deductionsController;
  late final TextEditingController _notesController;
  bool _saving = false;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _baseSalaryController = TextEditingController(
      text: widget.item.baseSalary.toStringAsFixed(2),
    );
    _quantityController = TextEditingController(
      text: widget.item.quantity == null ? '' : '${widget.item.quantity}',
    );
    _perUnitRateController = TextEditingController(
      text: widget.item.perUnitRate?.toStringAsFixed(2) ?? '',
    );
    _additionsController = TextEditingController(
      text: widget.item.additions.toStringAsFixed(2),
    );
    _deductionsController = TextEditingController(
      text: widget.item.deductions.toStringAsFixed(2),
    );
    _notesController = TextEditingController(text: widget.item.notes ?? '');
    for (final controller in [
      _baseSalaryController,
      _quantityController,
      _perUnitRateController,
      _additionsController,
      _deductionsController,
    ]) {
      controller.addListener(_onFieldChanged);
    }
  }

  void _onFieldChanged() => setState(() {});

  /// Mirrors the backend mapper: Quantity × Per unit replaces the salary
  /// snapshot as this run's base pay when both are set, then
  /// additions/deductions are applied on top — kept in sync here purely so
  /// the dialog can preview Net Pay live as the admin types.
  double get _previewNetPay {
    final quantity = int.tryParse(_quantityController.text);
    final perUnitRate = double.tryParse(_perUnitRateController.text);
    final baseSalary = double.tryParse(_baseSalaryController.text) ?? 0;
    final effectiveBase = (quantity != null && quantity > 0 && perUnitRate != null)
        ? quantity * perUnitRate
        : baseSalary;
    final additions = double.tryParse(_additionsController.text) ?? 0;
    final deductions = double.tryParse(_deductionsController.text) ?? 0;
    return effectiveBase + additions - deductions;
  }

  @override
  void dispose() {
    _baseSalaryController.dispose();
    _quantityController.dispose();
    _perUnitRateController.dispose();
    _additionsController.dispose();
    _deductionsController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    setState(() {
      _saving = true;
      _errorMessage = null;
    });
    try {
      await ref
          .read(payrollRepositoryProvider)
          .updateLineItem(
            widget.runId,
            widget.item.id,
            baseSalary: widget.item.isFreelancer
                ? double.tryParse(_baseSalaryController.text)
                : null,
            quantity: int.tryParse(_quantityController.text),
            perUnitRate: double.tryParse(_perUnitRateController.text),
            additions: double.tryParse(_additionsController.text),
            deductions: double.tryParse(_deductionsController.text),
            notes: _notesController.text.trim().isEmpty
                ? null
                : _notesController.text.trim(),
          );
      if (mounted) Navigator.of(context).pop();
    } on PayrollException catch (error) {
      setState(() => _errorMessage = error.message);
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.item.employeeName),
      content: SizedBox(
        width: 380,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              if (_errorMessage != null) ...[
                Text(
                  _errorMessage!,
                  style: TextStyle(color: Theme.of(context).colorScheme.error),
                ),
                const SizedBox(height: 12),
              ],
              if (widget.item.isFreelancer) ...[
                const _SectionLabel('Amount'),
                const SizedBox(height: 8),
                _AmountField(
                  label: 'This month\'s pay',
                  controller: _baseSalaryController,
                  enabled: !_saving,
                ),
              ] else
                Text(
                  'Salary snapshot: PKR ${formatAmount(widget.item.baseSalary)}',
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
              const SizedBox(height: 16),
              const _SectionLabel('Piece-rate pay (optional)'),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _quantityController,
                      enabled: !_saving,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(labelText: 'Quantity'),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _AmountField(
                      label: 'Per unit',
                      controller: _perUnitRateController,
                      enabled: !_saving,
                    ),
                  ),
                ],
              ),
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text(
                  'When both are set, Quantity × Per unit replaces the salary '
                  'snapshot as this run\'s base pay.',
                  style: Theme.of(context).textTheme.labelSmall?.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
              ),
              const SizedBox(height: 16),
              const _SectionLabel('Additions & Deductions'),
              const SizedBox(height: 8),
              Row(
                children: [
                  Expanded(
                    child: _AmountField(
                      label: 'Additions',
                      controller: _additionsController,
                      enabled: !_saving,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _AmountField(
                      label: 'Deductions',
                      controller: _deductionsController,
                      enabled: !_saving,
                    ),
                  ),
                ],
              ),
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text(
                  'Net Pay = Base + Additions − Deductions: '
                  'PKR ${formatAmount(_previewNetPay)}',
                  style: Theme.of(context).textTheme.labelMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    color: AppColors.primary,
                  ),
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: _notesController,
                enabled: !_saving,
                maxLines: 2,
                decoration: const InputDecoration(labelText: 'Notes (optional)'),
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _saving ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: _saving ? null : _submit,
          child: _saving
              ? const SizedBox(
                  height: 16,
                  width: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Save'),
        ),
      ],
    );
  }
}

class _AddFreelancerDialog extends ConsumerStatefulWidget {
  const _AddFreelancerDialog({required this.run});

  final PayrollRunDetail run;

  @override
  ConsumerState<_AddFreelancerDialog> createState() =>
      _AddFreelancerDialogState();
}

class _AddFreelancerDialogState extends ConsumerState<_AddFreelancerDialog> {
  String? _selectedFreelancerId;
  final _amountController = TextEditingController();
  final _notesController = TextEditingController();
  bool _saving = false;
  String? _errorMessage;

  @override
  void dispose() {
    _amountController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final freelancerId = _selectedFreelancerId;
    if (freelancerId == null) return;
    setState(() {
      _saving = true;
      _errorMessage = null;
    });
    try {
      await ref
          .read(payrollRepositoryProvider)
          .addFreelancerToRun(
            widget.run.id,
            freelancerId: freelancerId,
            baseSalary: double.tryParse(_amountController.text) ?? 0,
            notes: _notesController.text.trim().isEmpty
                ? null
                : _notesController.text.trim(),
          );
      if (mounted) Navigator.of(context).pop();
    } on PayrollException catch (error) {
      setState(() => _errorMessage = error.message);
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final freelancersAsync = ref.watch(freelancersListProvider);
    final alreadyInRun = widget.run.lineItems
        .map((item) => item.freelancerId)
        .whereType<String>()
        .toSet();

    return AlertDialog(
      title: const Text('Add Freelancer'),
      content: SizedBox(
        width: 380,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            if (_errorMessage != null) ...[
              Text(
                _errorMessage!,
                style: TextStyle(color: Theme.of(context).colorScheme.error),
              ),
              const SizedBox(height: 12),
            ],
            freelancersAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (_, _) => const Text('Could not load freelancers.'),
              data: (freelancers) {
                final available = freelancers
                    .where((f) => f.isActive && !alreadyInRun.contains(f.id))
                    .toList();
                if (available.isEmpty) {
                  return Text(
                    'No active freelancers left to add — everyone active is '
                    'already in this run.',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  );
                }
                return DropdownButtonFormField<String>(
                  initialValue: _selectedFreelancerId,
                  decoration: const InputDecoration(labelText: 'Freelancer'),
                  items: [
                    for (final freelancer in available)
                      DropdownMenuItem(
                        value: freelancer.id,
                        child: Text(freelancer.fullName),
                      ),
                  ],
                  onChanged: _saving
                      ? null
                      : (value) =>
                            setState(() => _selectedFreelancerId = value),
                );
              },
            ),
            const SizedBox(height: 12),
            _AmountField(
              label: "This month's pay",
              controller: _amountController,
              enabled: !_saving,
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _notesController,
              enabled: !_saving,
              maxLines: 2,
              decoration: const InputDecoration(labelText: 'Notes (optional)'),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: _saving ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: (_saving || _selectedFreelancerId == null)
              ? null
              : _submit,
          child: _saving
              ? const SizedBox(
                  height: 16,
                  width: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Add'),
        ),
      ],
    );
  }
}

class _SectionLabel extends StatelessWidget {
  const _SectionLabel(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Text(
      text.toUpperCase(),
      style: Theme.of(context).textTheme.labelSmall?.copyWith(
        color: AppColors.textSecondary,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.4,
      ),
    );
  }
}

class _AmountField extends StatelessWidget {
  const _AmountField({
    required this.label,
    required this.controller,
    required this.enabled,
  });

  final String label;
  final TextEditingController controller;
  final bool enabled;

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: controller,
      enabled: enabled,
      keyboardType: const TextInputType.numberWithOptions(decimal: true),
      decoration: InputDecoration(labelText: '$label (PKR)'),
    );
  }
}
